language: python
sudo: false
env:
  - python=2.7
    iris=1.9

  - python=2.7
    iris_from_source=master
    grib_api=1.14.7

#  - python=3.4
#    iris=master
#    grib_api=1.14.7

#  - python=3.5
#    iris=master
#    grib_api=1.14.7


install:
  # Fetch and install conda
  # -----------------------
  - export CONDA_BASE=http://repo.continuum.io/miniconda/Miniconda3
  - wget ${CONDA_BASE}-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda config --set show_channel_urls True
  - conda config --add channels conda-forge

  # Install iris-grib's dependencies
  # --------------------------------
  - |
     conda install --quiet --yes python=${python} pep8 pip nomkl \
            iris=${iris}* \
            python-ecmwf_grib=${grib_api}*

  # Fetch and install Iris from source
  # ----------------------------------
  - |
     if [ -n "$iris_from_source" ]; then
        conda remove --yes iris;
        wget https://github.com/scitools/iris/archive/${iris_from_source}.tar.gz -O iris.tar.gz;
        tar xzf iris.tar.gz && rm -rf iris.tar.gz && mv iris-${iris_from_source} iris_source;
        pip install ./iris_source --no-deps;
        rm -rf iris_source;
     fi

  # Download iris-test-data
  # --------------------------------
  - export IRIS_TEST_DATA_REF=https://github.com/SciTools/iris-test-data/archive/master.zip
  - export IRIS_TEST_DATA_LOCATION=$HOME/iris-test-data
  - mkdir $IRIS_TEST_DATA_LOCATION
  - wget -O $IRIS_TEST_DATA_LOCATION/iris-test-data.zip ${IRIS_TEST_DATA_REF}
  - unzip -q $IRIS_TEST_DATA_LOCATION/iris-test-data.zip -d $IRIS_TEST_DATA_LOCATION

  # Locate iris installation
  # ------------------------
  - export IRIS_DIR=$(python -c "import iris; import os.path; print os.path.dirname(iris.__file__)")

  # Poke site.cfg to reference iris-test-data
  - SITE_CFG=$IRIS_DIR/etc/site.cfg
  - echo "[Resources]" > $SITE_CFG
  - echo "test_data_dir = ${IRIS_TEST_DATA_LOCATION}/iris-test-data-master/test_data" >> $SITE_CFG

  # Install iris-grib itself
  # ------------------------
  - pip install . --no-deps

  # Install coveralls for test coverage
  # -----------------------------------
  - pip install coveralls

  # Summarise the environment
  # -------------------------
  - conda list

script:
  # Ensure we can import iris_grib and that the tests pass
  # ------------------------------------------------------
  - coverage run setup.py test

after_success: coveralls
